// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedAccountSummary } from "./SavedAccountSummary";

export type AccountListResponse = { data: Array<SavedAccountSummary>, nextCursor: string | null, activeSavedAccountId: string | null, };
